### ISSUE TITLE
Authorize无法登录，鉴权失败？

### ISSUE THREAD

**Issue by feixianghs** [wxq0309/fastapi#3]
![image](https://user-images.githubusercontent.com/39391774/78554511-dd569a80-783d-11ea-8b18-37388cb680ef.png)
请问这里无论如何都无法登录是什么情况？

**Comment by wxq0309** [comment]
> ![image](https://user-images.githubusercontent.com/39391774/78554511-dd569a80-783d-11ea-8b18-37388cb680ef.png)
> 请问这里无论如何都无法登录是什么情况？

图片没法正常显示，抱歉。可以写一下代码吗？

**Comment by feixianghs** [comment]
没有改你的代码，只是有点疑惑，我把截图上传到gitee上了，你看下链接内容。
https://images.gitee.com/uploads/images/2020/0406/195558_b7880a30_2019178.png
现在可以看到图片了吗？

**Comment by wxq0309** [comment]
已收到您的邮件图片。首先，您的想法是对的，不过仅仅改变tokenurl是不够的。无法用swagger文档中的Authorize有两个原因：&nbsp;第一，我在设置oauth2_scheme时并没有将tokenurl设置成 /user/login所以路由是没法正确匹配的。
第二，Authorize是默认的OAuth2PasswordRequestForm方式，需要输入username / password，但是我个人使用了JSON格式去登陆所以你这边尝试会失败。如果您想要在此登陆：可以先修改tokenurl，然后将user/login的请求体改为OAuth2PasswordRequestForm即可。



如果还有不太明白的地方可以继续邮件沟通。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "feixianghs"<notifications@github.com&gt;; 
发送时间: 2020年4月6日(星期一) 晚上7:57
收件人: "wxq0309/fastapi"<fastapi@noreply.github.com&gt;; 
抄送: "1053522308"<1053522308@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [wxq0309/fastapi] Authorize无法登录，鉴权失败？ (#3)





 
没有改你的代码，只是有点疑惑，我把截图上传到gitee上了，你看下链接内容。
 https://images.gitee.com/uploads/images/2020/0406/195558_b7880a30_2019178.png
 现在可以看到图片了吗？

**Comment by feixianghs** [comment]
非常感谢 @wxq0309
